### ISSUE TITLE
ProgressBar: If `taskname` is set using a `string` instead of `char`, the progress bar will be repetive

### ISSUE THREAD

**Issue by psychelzh** [elgar328/matlab-code-examples#2]
Sample code:

```matlab
N = 100;
PB = ProgressBar(N, taskname = "Test", ui = "cli");
for i = 1:N
    pause(0.1 * rand)
    PB.count
end
```

Output snapshot:

![image](https://github.com/elgar328/matlab-code-examples/assets/13306020/aa42eb0c-ca4a-4c97-8b2c-ac4e236d8dca)

If set as char type, it will be normal:

![image](https://github.com/elgar328/matlab-code-examples/assets/13306020/5959eed1-896e-4b36-b914-195de828d62f)

**Comment by elgar328** [comment]
"Thank you for letting me know. I have made the correction!"

<img width="726" alt="image" src="https://github.com/elgar328/matlab-code-examples/assets/93251045/72a38b5c-a12a-4ab0-811f-6e4433b6e061">
